from pathlib import Path

from buildrail.providers import ProviderGateway
from buildrail.providers.adapters.fake import FakeProvider
from buildrail.providers.errors import AuthenticationError
from buildrail.skill_protocol import RunContext, SkillRequest
from buildrail.skills import SkillRegistry

_SKILL_SOURCE = (
    Path(__file__).resolve().parents[3] / "skills" / "generate-docs" / "skill.py"
).read_text(encoding="utf-8")


def _request(inputs: dict[str, str]) -> SkillRequest:
    return SkillRequest(
        protocol_version="1.0",
        run_context=RunContext(run_id="20260804-000000-test", step_index=1, workdir="."),
        inputs=inputs,
        config={},
    )


def _write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def test_skill_source_never_imports_a_concrete_provider_adapter_or_core_internals() -> None:
    assert "import buildrail.providers.adapters" not in _SKILL_SOURCE
    assert "from buildrail.providers.adapters" not in _SKILL_SOURCE
    assert "import buildrail.core" not in _SKILL_SOURCE
    assert "from buildrail.core" not in _SKILL_SOURCE


def _sample_repo(tmp_path: Path) -> Path:
    _write(
        tmp_path / "pyproject.toml",
        '[project]\nname = "x"\nrequires-python = ">=3.12"\n'
        '[project.scripts]\nmytool = "app.main:run"\n'
        "[tool.ruff]\n[tool.mypy]\n[tool.pytest.ini_options]\n",
    )
    _write(tmp_path / "app" / "__init__.py", "")
    _write(tmp_path / "app" / "main.py", '"""Entry point."""\n\n\ndef run():\n    pass\n')
    _write(tmp_path / "tests" / "test_main.py", "def test_ok():\n    assert True\n")
    return tmp_path


def test_run_generates_all_three_documents_without_a_provider(tmp_path: Path) -> None:
    repo = _sample_repo(tmp_path)
    run_docs = SkillRegistry().resolve("generate-docs")

    response = run_docs(_request({"repository_path": str(repo)}), None)

    assert response.status == "success"
    assert set(response.outputs) == {"project_overview", "module_reference", "development_guide"}
    for output in response.outputs.values():
        assert output.artifact_type == "documentation"
        assert "Generated by Buildrail" in output.content
        assert output.metadata == {"enhanced": False}
        assert output.usage is None


def test_project_overview_contains_expected_facts(tmp_path: Path) -> None:
    repo = _sample_repo(tmp_path)
    run_docs = SkillRegistry().resolve("generate-docs")

    response = run_docs(_request({"repository_path": str(repo)}), None)

    content = response.outputs["project_overview"].content
    assert "mytool" in content
    assert "app.main:run" in content


def test_module_reference_lists_modules_and_local_imports(tmp_path: Path) -> None:
    repo = _sample_repo(tmp_path)
    _write(repo / "app" / "helper.py", "from app.main import run\n")
    run_docs = SkillRegistry().resolve("generate-docs")

    response = run_docs(_request({"repository_path": str(repo)}), None)

    content = response.outputs["module_reference"].content
    assert "app.helper" in content
    assert "app.main" in content


def test_development_guide_lists_discoverable_quality_commands(tmp_path: Path) -> None:
    repo = _sample_repo(tmp_path)
    run_docs = SkillRegistry().resolve("generate-docs")

    response = run_docs(_request({"repository_path": str(repo)}), None)

    content = response.outputs["development_guide"].content
    assert "ruff format --check ." in content
    assert "mypy" in content
    assert "pytest -v" in content


def test_run_does_not_construct_a_provider_without_enhance(tmp_path: Path) -> None:
    repo = _sample_repo(tmp_path)
    run_docs = SkillRegistry().resolve("generate-docs")

    # Passing provider=None and inputs without "enhance" must succeed — if the skill
    # tried to call a provider here, this would raise AttributeError on None.
    response = run_docs(_request({"repository_path": str(repo)}), None)

    assert response.status == "success"


def test_run_fails_cleanly_when_enhance_is_set_but_no_provider_is_supplied(
    tmp_path: Path,
) -> None:
    repo = _sample_repo(tmp_path)
    run_docs = SkillRegistry().resolve("generate-docs")

    response = run_docs(_request({"repository_path": str(repo), "enhance": "true"}), None)

    assert response.status == "failure"
    assert response.error is not None


def test_enhance_path_uses_only_the_provider_gateway_and_marks_metadata(tmp_path: Path) -> None:
    repo = _sample_repo(tmp_path)
    run_docs = SkillRegistry().resolve("generate-docs")
    gateway = ProviderGateway(FakeProvider())

    response = run_docs(_request({"repository_path": str(repo), "enhance": "true"}), gateway)

    assert response.status == "success"
    for output in response.outputs.values():
        assert output.metadata == {"enhanced": True}
        assert output.usage is not None
        assert output.model_used == "fake-model"


def test_enhancement_cannot_replace_deterministic_facts_with_invented_facts(
    tmp_path: Path,
) -> None:
    repo = _sample_repo(tmp_path)
    _write(repo / "app" / "helper.py", "from app.main import run\n")
    run_docs = SkillRegistry().resolve("generate-docs")

    enhanced = run_docs(
        _request({"repository_path": str(repo), "enhance": "true"}),
        ProviderGateway(FakeProvider()),
    )

    # The model is only ever asked for a short intro paragraph; every fact
    # (entry points, modules, quality commands) is always rendered by our
    # own deterministic code and must survive verbatim in the enhanced doc.
    assert "app.main:run" in enhanced.outputs["project_overview"].content
    assert "app.helper" in enhanced.outputs["module_reference"].content
    assert "app.main" in enhanced.outputs["module_reference"].content
    assert "pytest -v" in enhanced.outputs["development_guide"].content
    assert "mypy" in enhanced.outputs["development_guide"].content


def test_enhance_surfaces_provider_errors_as_a_failed_response(tmp_path: Path) -> None:
    repo = _sample_repo(tmp_path)
    run_docs = SkillRegistry().resolve("generate-docs")
    gateway = ProviderGateway(FakeProvider(error=AuthenticationError("no key")))

    response = run_docs(_request({"repository_path": str(repo), "enhance": "true"}), gateway)

    assert response.status == "failure"
    assert "no key" in (response.error or "")


def test_run_fails_cleanly_without_a_repository_path() -> None:
    run_docs = SkillRegistry().resolve("generate-docs")

    response = run_docs(_request({}), None)

    assert response.status == "failure"
