"""Scaffolds a new project-local skill under `.buildrail/skills/<name>/`.

Generates a minimal, immediately-runnable skill following the exact same
manifest and `SkillRequest`/`SkillResponse` protocol as built-in skills —
there is no separate scaffolding format. The manifest is rendered with
`yaml.safe_dump` (not string interpolation) so a free-text `description`
can never corrupt the YAML. Writes are atomic and refuse to overwrite an
existing skill directory; this module never deletes anything.
"""

import tempfile
from pathlib import Path

import yaml

from buildrail.extensions import (
    InvalidExtensionNameError,
    project_skills_dir,
    validate_extension_name,
)
from buildrail.skills.errors import SkillError

_MANIFEST_FILENAME = "skill.yaml"
_ENTRYPOINT_FILENAME = "skill.py"
_DEFAULT_DESCRIPTION = "A project-local Buildrail skill."

_PROVIDER_FREE_TEMPLATE = '''\
"""{name}: a project-local Buildrail skill.

Project-local skills execute code from this repository — only use
project-local skills from repositories you trust. This follows the same
SkillRequest/SkillResponse contract every built-in skill uses
(docs/skills.md).
"""

from buildrail.skill_protocol import SkillOutput, SkillRequest, SkillResponse


def run(request: SkillRequest, provider: object | None) -> SkillResponse:
    """Produce a minimal, valid artifact. Replace this with real logic."""
    content = "# {name}\\n\\nGenerated by the {name} skill.\\n"
    output = SkillOutput(content=content, artifact_type="{name}", display_name="{name}-summary")
    return SkillResponse(status="success", outputs={{"summary": output}})
'''

_REQUIRES_PROVIDER_TEMPLATE = '''\
"""{name}: a project-local Buildrail skill that uses the configured provider.

Project-local skills execute code from this repository — only use
project-local skills from repositories you trust. `provider` is a
ProviderGateway, exactly as for a built-in skill — this skill never
imports a vendor SDK directly (docs/provider-interface.md).
"""

from buildrail.providers import Message, ProviderError, ProviderGateway, ProviderRequest, TextPart
from buildrail.skill_protocol import SkillOutput, SkillRequest, SkillResponse


def run(request: SkillRequest, provider: ProviderGateway) -> SkillResponse:
    """Ask the configured provider for a short response. Replace this with real logic."""
    provider_request = ProviderRequest(
        messages=(Message(role="user", content=(TextPart(text="Say hello."),)),)
    )
    try:
        provider_response = provider.complete(provider_request)
    except ProviderError as exc:
        return SkillResponse(status="failure", outputs={{}}, error=str(exc))

    output = SkillOutput(
        content=provider_response.content,
        artifact_type="{name}",
        display_name="{name}-summary",
        model_used=provider_response.model_used,
        usage=provider_response.usage,
    )
    return SkillResponse(status="success", outputs={{"summary": output}})
'''


class SkillScaffoldError(SkillError):
    """Raised when a project-local skill cannot be scaffolded."""


def create_skill(
    project_root: Path,
    name: str,
    *,
    description: str = _DEFAULT_DESCRIPTION,
    requires_provider: bool = False,
) -> Path:
    """Scaffold `.buildrail/skills/<name>/skill.yaml` + `skill.py` and return its directory.

    Raises `SkillScaffoldError` (wrapping name/description validation
    failures too) if `name` is unsafe or a skill directory already exists
    at that path — this never overwrites existing project-local content.
    """
    try:
        validate_extension_name(name, label="skill name")
    except InvalidExtensionNameError as exc:
        raise SkillScaffoldError(str(exc)) from exc
    if not isinstance(description, str) or not description:
        raise SkillScaffoldError("Skill description must be a non-empty string.")

    skill_dir = project_skills_dir(project_root) / name
    if skill_dir.exists():
        raise SkillScaffoldError(f"A project-local skill already exists at {skill_dir}.")

    manifest_document = {
        "name": name,
        "version": "0.1.0",
        "protocol_version": "1.0",
        "description": description,
        "entrypoint": "python skill.py",
        "inputs": [],
        "outputs": [{"name": "summary", "artifact_type": name}],
        "requires_provider": requires_provider,
    }
    manifest_text = yaml.safe_dump(manifest_document, sort_keys=False, default_flow_style=False)
    skill_template = _REQUIRES_PROVIDER_TEMPLATE if requires_provider else _PROVIDER_FREE_TEMPLATE

    skill_dir.mkdir(parents=True, exist_ok=False)
    try:
        _atomic_write(skill_dir / _MANIFEST_FILENAME, manifest_text)
        _atomic_write(skill_dir / _ENTRYPOINT_FILENAME, skill_template.format(name=name))
    except BaseException:
        _remove_if_empty(skill_dir)
        raise
    return skill_dir


def _atomic_write(path: Path, content: str) -> None:
    fd, tmp_name = tempfile.mkstemp(prefix=".buildrail-scaffold-", dir=path.parent)
    tmp_path = Path(tmp_name)
    try:
        with open(fd, "w", encoding="utf-8") as handle:
            handle.write(content)
        tmp_path.replace(path)
    except BaseException:
        tmp_path.unlink(missing_ok=True)
        raise


def _remove_if_empty(directory: Path) -> None:
    try:
        next(directory.iterdir())
    except StopIteration:
        directory.rmdir()
    except OSError:
        pass
