"""The generate-docs skill: renders deterministic Markdown docs from a ProjectAnalysis.

Provider-neutral, like review-diff — only imports buildrail.providers' public
Gateway and request/response types, never a concrete adapter, and only ever
calls the provider when the caller explicitly opts in (`inputs["enhance"] ==
"true"`) and passes a real ProviderGateway. Without --enhance, `provider` is
always None and this module never touches it. When enhancing, at most one
provider request is made per generated document, and only to draft a short
introductory paragraph — every factual section (commands, modules, imports,
statistics) is always rendered deterministically from the analysis, never by
the model, so enhancement cannot replace or invent facts.
"""

import json
from pathlib import Path

from buildrail.analysis import (
    AnalysisError,
    ProjectAnalysis,
    analysis_from_dict,
    analyze_project,
    suggested_reading_order,
)
from buildrail.providers import (
    Message,
    ProviderError,
    ProviderGateway,
    ProviderRequest,
    ProviderResponse,
    TextPart,
)
from buildrail.skill_protocol import SkillOutput, SkillRequest, SkillResponse

_NOTICE = "> Generated by Buildrail (`generate-docs`) — do not edit by hand.\n"


def run(request: SkillRequest, provider: ProviderGateway | None) -> SkillResponse:
    """Generate project-overview.md, module-reference.md, and development-guide.md."""
    repository_path = request.inputs.get("repository_path")
    if not repository_path:
        return SkillResponse(status="failure", outputs={}, error="No repository_path provided.")

    analysis_json_path = request.inputs.get("analysis_json")
    try:
        if analysis_json_path:
            data = json.loads(Path(analysis_json_path).read_text(encoding="utf-8"))
            analysis = analysis_from_dict(data)
        else:
            analysis = analyze_project(Path(repository_path))
    except (AnalysisError, OSError, json.JSONDecodeError, KeyError) as exc:
        return SkillResponse(
            status="failure", outputs={}, error=f"Could not analyze project: {exc}"
        )

    enhance = request.inputs.get("enhance") == "true"
    if enhance and provider is None:
        return SkillResponse(
            status="failure", outputs={}, error="--enhance was set but no provider was supplied."
        )

    drafts = {
        "project_overview": ("Project Overview", _build_overview(analysis)),
        "module_reference": ("Module Reference", _build_module_reference(analysis)),
        "development_guide": ("Development Guide", _build_development_guide(analysis)),
    }

    outputs: dict[str, SkillOutput] = {}
    for key, (title, body) in drafts.items():
        content = body
        model_used = None
        usage = None
        if enhance:
            assert provider is not None
            try:
                intro, provider_response = _enhance_intro(provider, title, body)
            except ProviderError as exc:
                return SkillResponse(status="failure", outputs={}, error=str(exc))
            content = f"# {title}\n\n{_NOTICE}\n{intro}\n\n{body}"
            model_used = provider_response.model_used
            usage = provider_response.usage
        else:
            content = f"# {title}\n\n{_NOTICE}\n{body}"
        outputs[key] = SkillOutput(
            content=content.rstrip() + "\n",
            artifact_type="documentation",
            display_name=key.replace("_", "-"),
            model_used=model_used,
            usage=usage,
            metadata={"enhanced": enhance},
        )

    return SkillResponse(status="success", outputs=outputs)


def _enhance_intro(
    provider: ProviderGateway, title: str, body: str
) -> tuple[str, ProviderResponse]:
    prompt = (
        "Write a concise, 2-4 sentence prose introduction for a generated "
        f"documentation page titled '{title}'. Base it only on the facts below; "
        "do not invent commands, modules, APIs, or architecture not listed here.\n\n"
        f"{body}"
    )
    provider_request = ProviderRequest(
        messages=(Message(role="user", content=(TextPart(text=prompt),)),)
    )
    response = provider.complete(provider_request)
    return response.content.strip(), response


def _build_overview(analysis: ProjectAnalysis) -> str:
    lines = ["## What This Repository Contains", ""]
    lines.append(f"- Root: `{analysis.repository_root}`")
    if analysis.python_requires:
        lines.append(f"- Python requires: `{analysis.python_requires}`")
    if analysis.build_system:
        lines.append(f"- Build backend: `{analysis.build_system}`")
    lines.append("")

    if analysis.entry_points:
        lines.append("## Primary Entry Points")
        lines.append("")
        for entry in analysis.entry_points:
            lines.append(f"- `{entry.name}` -> `{entry.target}`")
        lines.append("")

    lines.append("## Package Map")
    lines.append("")
    for package in analysis.packages:
        lines.append(f"- `{package.dotted_name}/` ({len(package.modules)} module(s))")
    top_level = sorted(m.dotted_name for m in analysis.modules if "." not in m.dotted_name)
    for module in top_level:
        lines.append(f"- `{module}`")
    lines.append("")

    if analysis.cli_commands:
        lines.append("## Available CLI Commands")
        lines.append("")
        for command in analysis.cli_commands:
            suffix = f" — {command.description}" if command.description else ""
            lines.append(f"- `{command.command}`{suffix}")
        lines.append("")

    if analysis.skills or analysis.pipelines:
        lines.append("## Buildrail Skills and Pipelines")
        lines.append("")
        for skill in analysis.skills:
            lines.append(f"- skill `{skill.name}` ({skill.version})")
        for pipeline in analysis.pipelines:
            lines.append(f"- pipeline `{pipeline.name}`: {' -> '.join(pipeline.steps)}")
        lines.append("")

    return "\n".join(lines)


def _build_module_reference(analysis: ProjectAnalysis) -> str:
    if not analysis.modules:
        return "_No Python modules discovered._\n"
    lines: list[str] = []
    for module in analysis.modules:
        lines.append(f"## `{module.dotted_name}`")
        lines.append("")
        if module.docstring:
            lines.append(f"_{module.docstring}_")
            lines.append("")
        if module.classes:
            lines.append("**Classes:**")
            for cls in module.classes:
                suffix = f" — {cls.docstring}" if cls.docstring else ""
                lines.append(f"- `{cls.name}`{suffix}")
            lines.append("")
        if module.functions:
            lines.append("**Functions:**")
            for func in module.functions:
                suffix = f" — {func.docstring}" if func.docstring else ""
                lines.append(f"- `{func.name}`{suffix}")
            lines.append("")
        if module.imports:
            lines.append("**Local imports:**")
            for imported in module.imports:
                lines.append(f"- `{imported}`")
            lines.append("")
    return "\n".join(lines)


def _build_development_guide(analysis: ProjectAnalysis) -> str:
    lines = ["## Requirements", ""]
    lines.append(f"- Python: `{analysis.python_requires or 'not declared'}`")
    lines.append(f"- Build backend: `{analysis.build_system or 'not declared'}`")
    lines.append("")

    commands = []
    if analysis.tooling.has_ruff:
        commands.extend(["ruff format --check .", "ruff check ."])
    if analysis.tooling.has_mypy:
        commands.append("mypy")
    if analysis.tooling.has_pytest:
        commands.append("pytest -v")
    lines.append("## Quality and Test Commands")
    lines.append("")
    if commands:
        for command in commands:
            lines.append(f"- `{command}`")
    else:
        lines.append("_No quality/test commands were deterministically discoverable._")
    lines.append("")

    lines.append("## Test Layout")
    lines.append("")
    if analysis.test_layout.test_directories or analysis.test_layout.test_files:
        for directory in analysis.test_layout.test_directories:
            lines.append(f"- `{directory}/`")
        lines.append(f"- {len(analysis.test_layout.test_files)} test file(s) total")
    else:
        lines.append("_No test files discovered._")
    lines.append("")

    order = suggested_reading_order(analysis)
    if order:
        lines.append("## Suggested Reading Order")
        lines.append("")
        for i, dotted in enumerate(order, start=1):
            lines.append(f"{i}. `{dotted}`")
        lines.append("")

    return "\n".join(lines)
