"""The generate-diagram skill: renders deterministic Mermaid source from a ProjectAnalysis.

Provider-free, network-free, and never executes Mermaid or any external
renderer — this skill only ever produces Mermaid *source text*. Only the
`mermaid` format is supported in this slice (no SVG/PNG rendering). Node
identifiers are derived deterministically from stable analysis facts (dotted
module names, skill names, artifact types), and a module dependency graph
larger than `_MAX_NODES` is summarized at package granularity rather than
silently dropping nodes.
"""

import json
from pathlib import Path

from buildrail.analysis import AnalysisError, ProjectAnalysis, analysis_from_dict, analyze_project
from buildrail.skill_protocol import SkillOutput, SkillRequest, SkillResponse

_NOTICE = "> Generated by Buildrail (`generate-diagram`) — do not edit by hand."
_MAX_NODES = 40
_MAX_LABEL_CHARS = 60


def run(request: SkillRequest, provider: object | None) -> SkillResponse:
    """Analyze the requested repository and produce a Mermaid diagram artifact."""
    diagram_format = request.inputs.get("format", "mermaid")
    if diagram_format != "mermaid":
        return SkillResponse(
            status="failure",
            outputs={},
            error=f"Unsupported diagram format '{diagram_format}'; only 'mermaid' is supported.",
        )

    repository_path = request.inputs.get("repository_path")
    if not repository_path:
        return SkillResponse(status="failure", outputs={}, error="No repository_path provided.")

    analysis_json_path = request.inputs.get("analysis_json")
    try:
        if analysis_json_path:
            data = json.loads(Path(analysis_json_path).read_text(encoding="utf-8"))
            analysis = analysis_from_dict(data)
        else:
            analysis = analyze_project(Path(repository_path))
    except (AnalysisError, OSError, json.JSONDecodeError, KeyError) as exc:
        return SkillResponse(
            status="failure", outputs={}, error=f"Could not analyze project: {exc}"
        )

    output = SkillOutput(
        content=_build_diagrams(analysis),
        artifact_type="diagram",
        display_name="architecture-diagrams",
    )
    return SkillResponse(status="success", outputs={"diagrams": output})


def _node_id(prefix: str, name: str) -> str:
    safe = "".join(char if char.isalnum() or char == "_" else "_" for char in name)
    if not safe or safe[0].isdigit():
        safe = f"n_{safe}"
    return f"{prefix}_{safe}"


def _escape_label(text: str) -> str:
    cleaned = text.replace("\n", " ").replace('"', "'")
    if len(cleaned) > _MAX_LABEL_CHARS:
        cleaned = cleaned[: _MAX_LABEL_CHARS - 3] + "..."
    return cleaned


def _mermaid_block(
    title: str, nodes: dict[str, str], edges: list[tuple[str, str]], note: str | None = None
) -> str:
    lines = [f"## {title}", ""]
    if note:
        lines.append(f"_{note}_")
        lines.append("")
    lines.append("```mermaid")
    lines.append("graph TD")
    for node_id, label in nodes.items():
        lines.append(f'    {node_id}["{_escape_label(label)}"]')
    for source, target in edges:
        lines.append(f"    {source} --> {target}")
    lines.append("```")
    lines.append("")
    return "\n".join(lines)


def _module_dependency_diagram(analysis: ProjectAnalysis) -> str:
    modules = analysis.modules
    if not modules:
        return _mermaid_block("Module Dependencies", {}, [], note="No Python modules discovered.")

    if len(modules) <= _MAX_NODES:
        nodes = {_node_id("m", m.dotted_name): m.dotted_name for m in modules}
        edges: list[tuple[str, str]] = []
        seen: set[tuple[str, str]] = set()
        for module in modules:
            source_id = _node_id("m", module.dotted_name)
            for imported in module.imports:
                if imported == module.dotted_name:
                    continue
                target_id = _node_id("m", imported)
                if target_id not in nodes:
                    continue
                pair = (source_id, target_id)
                if pair not in seen:
                    seen.add(pair)
                    edges.append(pair)
        return _mermaid_block("Module Dependencies", nodes, edges)

    # Group by each module's top-level directory (not its dotted name): a
    # `__init__.py`-free test directory would otherwise produce one noisy
    # "group" per file, since each such file's dotted name has no dot. Loose
    # top-level files (no directory at all) share one "(root)" bucket rather
    # than each becoming its own single-module group.
    group_by_dotted = {
        m.dotted_name: (m.file_path.split("/", 1)[0] if "/" in m.file_path else "(root)")
        for m in modules
    }
    groups = sorted(set(group_by_dotted.values()))
    nodes = {_node_id("pkg", group): group for group in groups}
    edges = []
    seen = set()
    for module in modules:
        source_group = group_by_dotted[module.dotted_name]
        for imported in module.imports:
            target_group = group_by_dotted.get(imported)
            if target_group is None or target_group == source_group:
                continue
            pair = (_node_id("pkg", source_group), _node_id("pkg", target_group))
            if pair not in seen:
                seen.add(pair)
                edges.append(pair)
    note = (
        f"{len(modules)} modules exceed the {_MAX_NODES}-node limit; grouped by top-level package."
    )
    return _mermaid_block("Module Dependencies (by Package)", nodes, edges, note=note)


def _runtime_diagram(analysis: ProjectAnalysis) -> str | None:
    if not analysis.skills and not analysis.pipelines:
        return None
    nodes: dict[str, str] = {}
    edges: list[tuple[str, str]] = []
    cli_id = _node_id("cli", "cli")
    nodes[cli_id] = "CLI"

    steps_in_pipelines: set[str] = set()
    for pipeline in analysis.pipelines:
        pipeline_id = _node_id("pipeline", pipeline.name)
        nodes[pipeline_id] = f"pipeline: {pipeline.name}"
        edges.append((cli_id, pipeline_id))
        for step in pipeline.steps:
            steps_in_pipelines.add(step)
            skill_id = _node_id("skill", step)
            nodes.setdefault(skill_id, f"skill: {step}")
            edges.append((pipeline_id, skill_id))

    for skill in analysis.skills:
        if skill.name in steps_in_pipelines:
            continue
        skill_id = _node_id("skill", skill.name)
        nodes.setdefault(skill_id, f"skill: {skill.name}")
        edges.append((cli_id, skill_id))

    return _mermaid_block("Buildrail Runtime", nodes, edges)


def _skill_artifact_diagram(analysis: ProjectAnalysis) -> str | None:
    if not analysis.skills:
        return None
    nodes: dict[str, str] = {}
    edges: list[tuple[str, str]] = []
    for skill in analysis.skills:
        skill_id = _node_id("skill", skill.name)
        nodes[skill_id] = f"skill: {skill.name}"
        for artifact_type in skill.artifact_types:
            artifact_id = _node_id("artifact", artifact_type)
            nodes.setdefault(artifact_id, f"artifact: {artifact_type}")
            edges.append((skill_id, artifact_id))
    return _mermaid_block("Skill to Artifact", nodes, edges)


def _build_diagrams(analysis: ProjectAnalysis) -> str:
    sections = [
        f"# Architecture Diagrams: {analysis.repository_name}",
        "",
        _NOTICE,
        "",
        _module_dependency_diagram(analysis),
    ]
    runtime = _runtime_diagram(analysis)
    if runtime:
        sections.append(runtime)
    skill_artifact = _skill_artifact_diagram(analysis)
    if skill_artifact:
        sections.append(skill_artifact)
    return "\n".join(sections).rstrip() + "\n"
